// <auto-generated />
using System;
using System.Collections.Generic;
using DysonNetwork.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WattEngine.Ideask;

#nullable disable

namespace WattEngine.Ideask.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20260726124527_MakeGitHubBoardRelationshipManyToOne")]
    partial class MakeGitHubBoardRelationshipManyToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtBroad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<SnCloudFileReferenceObject>("BackgroundImage")
                        .HasColumnType("jsonb")
                        .HasColumnName("background_image");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<SnCloudFileReferenceObject>("IconImage")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_broads");

                    b.ToTable("broads", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubCommentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("GitHubCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_comment_id");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_comment_links");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_git_hub_comment_links_comment_id");

                    b.HasIndex("GitHubCommentId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_comment_links_git_hub_comment_id");

                    b.HasIndex("IntegrationId", "CommentId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_comment_links_integration_id_comment_id");

                    b.ToTable("git_hub_comment_links", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubInstallationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("state");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_installation_grants");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_installation_grants_state");

                    b.HasIndex("WorkspaceId", "AccountId")
                        .HasDatabaseName("ix_git_hub_installation_grants_workspace_id_account_id");

                    b.ToTable("git_hub_installation_grants", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BroadId")
                        .HasColumnType("uuid")
                        .HasColumnName("broad_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("GitHubRepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_repository_id");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("last_error");

                    b.Property<Instant?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("repository");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_integrations");

                    b.HasIndex("BroadId")
                        .HasDatabaseName("ix_git_hub_integrations_broad_id");

                    b.HasIndex("GitHubRepositoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_integrations_git_hub_repository_id");

                    b.ToTable("git_hub_integrations", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubIssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("GitHubIssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_issue_id");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("html_url");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<Instant?>("LastGitHubUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_git_hub_updated_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_git_hub_issue_links");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_git_hub_issue_links_task_id");

                    b.HasIndex("IntegrationId", "GitHubIssueId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_issue_links_integration_id_git_hub_issue_id");

                    b.HasIndex("IntegrationId", "TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_hub_issue_links_integration_id_task_id");

                    b.ToTable("git_hub_issue_links", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<SnCloudFileReferenceObject>>("Attachments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments");

                    b.Property<Guid>("BroadId")
                        .HasColumnType("uuid")
                        .HasColumnName("broad_id");

                    b.Property<int?>("CompleteReason")
                        .HasColumnType("integer")
                        .HasColumnName("complete_reason");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_task_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("BroadId")
                        .HasDatabaseName("ix_tasks_broad_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_tasks_group_id");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("ix_tasks_parent_task_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskAssignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_assignees");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_task_assignees_account_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_assignees_task_id");

                    b.ToTable("task_assignees", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExternalAuthorAvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_author_avatar_url");

                    b.Property<string>("ExternalAuthorLogin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_author_login");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_task_comments_task_id_created_at");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BroadId")
                        .HasColumnType("uuid")
                        .HasColumnName("broad_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_groups");

                    b.HasIndex("BroadId", "Position")
                        .HasDatabaseName("ix_task_groups_broad_id_position");

                    b.ToTable("task_groups", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubCommentLink", b =>
                {
                    b.HasOne("WattEngine.Ideask.Task.WtTaskComment", "Comment")
                        .WithMany("GitHubComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_comment_links_task_comments_comment_id");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubIntegration", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtBroad", "Broad")
                        .WithMany()
                        .HasForeignKey("BroadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_integrations_broads_broad_id");

                    b.Navigation("Broad");
                });

            modelBuilder.Entity("WattEngine.Ideask.GitHub.WtGitHubIssueLink", b =>
                {
                    b.HasOne("WattEngine.Ideask.GitHub.WtGitHubIntegration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_links_git_hub_integrations_integration_id");

                    b.HasOne("WattEngine.Ideask.Task.WtTask", "Task")
                        .WithMany("GitHubIssues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_links_tasks_task_id");

                    b.Navigation("Integration");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtBroad", "Broad")
                        .WithMany()
                        .HasForeignKey("BroadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_broads_broad_id");

                    b.HasOne("WattEngine.Ideask.Task.WtTaskGroup", "Group")
                        .WithMany("Tasks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_task_groups_group_id");

                    b.HasOne("WattEngine.Ideask.Task.WtTask", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_tasks_parent_task_id");

                    b.Navigation("Broad");

                    b.Navigation("Group");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskAssignee", b =>
                {
                    b.HasOne("WattEngine.Ideask.Task.WtTask", "Task")
                        .WithMany("Assignees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_assignees_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskComment", b =>
                {
                    b.HasOne("WattEngine.Ideask.Task.WtTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskGroup", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtBroad", "Broad")
                        .WithMany()
                        .HasForeignKey("BroadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_groups_broads_broad_id");

                    b.Navigation("Broad");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Comments");

                    b.Navigation("GitHubIssues");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskComment", b =>
                {
                    b.Navigation("GitHubComments");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTaskGroup", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
