// <auto-generated />
using System;
using System.Collections.Generic;
using DysonNetwork.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WattEngine.Ideask;

#nullable disable

namespace WattEngine.Ideask.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20260124171338_EnrichBroadAndProject")]
    partial class EnrichBroadAndProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtBroad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<SnCloudFileReferenceObject>("BackgroundImage")
                        .HasColumnType("jsonb")
                        .HasColumnName("background_image");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<SnCloudFileReferenceObject>("IconImage")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_broads");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_broads_project_id");

                    b.ToTable("broads", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_creator");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_members_project_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<SnCloudFileReferenceObject>>("Attachments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments");

                    b.Property<Guid>("BroadId")
                        .HasColumnType("uuid")
                        .HasColumnName("broad_id");

                    b.Property<int?>("CompleteReason")
                        .HasColumnType("integer")
                        .HasColumnName("complete_reason");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_task_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("BroadId")
                        .HasDatabaseName("ix_tasks_broad_id");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("ix_tasks_parent_task_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("WtProjectMemberWtTask", b =>
                {
                    b.Property<Guid>("AssigneesId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignees_id");

                    b.Property<Guid>("WtTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("wt_task_id");

                    b.HasKey("AssigneesId", "WtTaskId")
                        .HasName("pk_wt_task_assignees");

                    b.HasIndex("WtTaskId")
                        .HasDatabaseName("ix_wt_task_assignees_wt_task_id");

                    b.ToTable("WtTaskAssignees", (string)null);
                });

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtBroad", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtProject", "Project")
                        .WithMany("Broads")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_broads_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtProjectMember", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtProject", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtBroad", "Broad")
                        .WithMany()
                        .HasForeignKey("BroadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_broads_broad_id");

                    b.HasOne("WattEngine.Ideask.Task.WtTask", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_tasks_parent_task_id");

                    b.Navigation("Broad");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("WtProjectMemberWtTask", b =>
                {
                    b.HasOne("WattEngine.Ideask.Broad.WtProjectMember", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wt_task_assignees_project_members_assignees_id");

                    b.HasOne("WattEngine.Ideask.Task.WtTask", null)
                        .WithMany()
                        .HasForeignKey("WtTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wt_task_assignees_tasks_wt_task_id");
                });

            modelBuilder.Entity("WattEngine.Ideask.Broad.WtProject", b =>
                {
                    b.Navigation("Broads");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("WattEngine.Ideask.Task.WtTask", b =>
                {
                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
