#!/usr/bin/env bash
#
# Computes which services to build and writes .circleci/continue_config.yml.
#
# Mirrors the logic of .github/workflows/docker-build.yml:
#   - API/UI trigger (workflow_dispatch): build $MODULE ("all" or one service).
#   - Push to master: build services whose directory changed; any change under
#     DysonNetwork.Shared (the NeTo submodule) rebuilds every service.
#
# Inputs (environment):
#   TRIGGER_SOURCE  - << pipeline.trigger_source >> (api | webhook | ...)
#   MODULE          - << pipeline.parameters.module >> ("all" or a service name)
#
# Output: .circleci/continue_config.yml
set -euo pipefail

SERVICES=(Ideask Valve Flywheel)
IMAGES=(ideask valve flywheel)

items=()  # "Service:image" pairs to build

contains() {
    local item="$1"
    shift
    local e
    for e in "$@"; do
        [ "$e" = "$item" ] && return 0
    done
    return 1
}

add_service() {
    local service="$1"
    local i
    for i in "${!SERVICES[@]}"; do
        if [ "${SERVICES[$i]}" = "$service" ]; then
            items+=("${SERVICES[$i]}:${IMAGES[$i]}")
            return
        fi
    done
}

build_all() {
    items=()
    local i
    for i in "${!SERVICES[@]}"; do
        items+=("${SERVICES[$i]}:${IMAGES[$i]}")
    done
}

if [ "$TRIGGER_SOURCE" = "api" ] || [ "$TRIGGER_SOURCE" = "ui" ]; then
    if [ "$MODULE" = "all" ]; then
        build_all
    else
        add_service "$MODULE"
    fi
else
    # Push: diff against the previously built commit.
    [ -n "${CIRCLE_SHA1:-}" ] || CIRCLE_SHA1="$(git rev-parse HEAD)"
    before=""
    if [ -n "${CIRCLE_COMPARE_URL:-}" ]; then
        before="${CIRCLE_COMPARE_URL##*/compare/}"
        before="${before%%...*}"
    fi
    [ -n "$before" ] || before="$(git rev-parse HEAD~1 2>/dev/null || true)"

    if [ -n "$before" ] && git cat-file -e "$before^{commit}" 2>/dev/null; then
        changed=()
        submodule_changed=false
        while IFS= read -r file; do
            case "$file" in
                DysonNetwork.Shared | DysonNetwork.Shared/*)
                    submodule_changed=true
                    ;;
                WattEngine.*/*)
                    service="${file#WattEngine.}"
                    service="${service%%/*}"
                    if contains "$service" "${SERVICES[@]}" \
                        && { [ ${#changed[@]} -eq 0 ] || ! contains "$service" "${changed[@]}"; }; then
                        changed+=("$service")
                    fi
                    ;;
            esac
        done < <(git diff --name-only "$before" "$CIRCLE_SHA1")

        if [ "$submodule_changed" = true ]; then
            build_all
        else
            items=()
            if [ ${#changed[@]} -gt 0 ]; then
                for s in "${changed[@]}"; do
                    add_service "$s"
                done
            fi
        fi
    else
        # No prior commit (first push) - build everything.
        build_all
    fi
fi

out=".circleci/continue_config.yml"

emit_header() {
    cat <<'EOF'
# Generated by .circleci/scripts/generate_config.sh - do not edit by hand.
# Mirrors the build-and-push job of .github/workflows/docker-build.yml.
version: 2.1

jobs:
  build-and-push:
    machine: true
    parameters:
      service:
        type: string
      image:
        type: string
    steps:
      - checkout
      - run:
          name: Sync submodules
          command: git submodule sync && git submodule update --init --recursive
      - run:
          name: Build and push Docker image
          command: |
            set -euo pipefail
            # Credentials: CircleCI Project Settings -> Environment Variables
            base="ghcr.io/${PACKAGE_OWNER:?Set PACKAGE_OWNER (GHCR namespace) in CircleCI Project Settings > Environment Variables}/watt-<< parameters.image >>"
            echo "${GHCR_TOKEN:?Set GHCR_TOKEN (GitHub PAT with write:packages) in CircleCI Project Settings > Environment Variables}" | docker login ghcr.io -u "${GHCR_USERNAME:?Set GHCR_USERNAME (token owner) in CircleCI Project Settings > Environment Variables}" --password-stdin
            # Versioned tag dropped (no version.json; nbgv yielded 0.0.0) - latest only.
            docker build --platform linux/amd64 \
              -f "WattEngine.<< parameters.service >>/Dockerfile" \
              -t "${base}:latest" \
              .
            docker push "${base}:latest"
EOF
}

if [ ${#items[@]} -eq 0 ]; then
    {
        emit_header
        cat <<'EOF'

workflows:
  build:
    when: false  # No services changed; nothing to build.
    jobs:
      - build-and-push:
          name: skip
          service: Ideask
          image: ideask
EOF
    } > "$out"
    exit 0
fi

{
    emit_header
    cat <<'EOF'

workflows:
  build:
    jobs:
EOF
    for item in "${items[@]}"; do
        service="${item%%:*}"
        image="${item#*:}"
        name="build-$(printf '%s' "$service" | tr '[:upper:]' '[:lower:]')"
        printf '      - build-and-push:\n          name: %s\n          service: %s\n          image: %s\n' "$name" "$service" "$image"
    done
} > "$out"
