// <auto-generated />
using System;
using DysonNetwork.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WattEngine.Valve;

#nullable disable

namespace WattEngine.Valve.Migrations
{
    [DbContext(typeof(AppDatabase))]
    partial class AppDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<SnCloudFileReferenceObject>("Background")
                        .HasColumnType("jsonb")
                        .HasColumnName("background");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<SnCloudFileReferenceObject>("Picture")
                        .HasColumnType("jsonb")
                        .HasColumnName("picture");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<Instant?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_expires_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("slug");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Slug", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_slug_deleted_at");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceBilling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("currency");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_amount");

                    b.Property<Instant?>("NextBillingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_at");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("payment_method_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_billings");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_billings_workspace_id");

                    b.ToTable("workspace_billings", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("currency");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_invoices");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_invoices_workspace_id");

                    b.ToTable("workspace_invoices", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Instant?>("LeaveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("WorkspaceId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_account_id");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanCreateProjects")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_projects");

                    b.Property<bool>("CanManageBilling")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_billing");

                    b.Property<bool>("CanManageMembers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_members");

                    b.Property<bool>("CanManageProjects")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_projects");

                    b.Property<bool>("CanManageWorkspace")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_workspace");

                    b.Property<bool>("CanUseDrive")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_drive");

                    b.Property<bool>("CanUseIdeask")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_ideask");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("RoleLevel")
                        .HasColumnType("integer")
                        .HasColumnName("role_level");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_role_permissions");

                    b.HasIndex("WorkspaceId", "RoleLevel")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_role_permissions_workspace_id_role_level");

                    b.ToTable("workspace_role_permissions", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceUserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("CanCreateProjects")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create_projects");

                    b.Property<bool?>("CanManageBilling")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_billing");

                    b.Property<bool?>("CanManageMembers")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_members");

                    b.Property<bool?>("CanManageProjects")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_projects");

                    b.Property<bool?>("CanManageWorkspace")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_workspace");

                    b.Property<bool?>("CanUseDrive")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_drive");

                    b.Property<bool?>("CanUseIdeask")
                        .HasColumnType("boolean")
                        .HasColumnName("can_use_ideask");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_user_permissions");

                    b.HasIndex("WorkspaceId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_user_permissions_workspace_id_account_id");

                    b.ToTable("workspace_user_permissions", (string)null);
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceBilling", b =>
                {
                    b.HasOne("WattEngine.Valve.Workspace.WtWorkspace", "Workspace")
                        .WithMany("Billings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_billings_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceInvoice", b =>
                {
                    b.HasOne("WattEngine.Valve.Workspace.WtWorkspace", "Workspace")
                        .WithMany("Invoices")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invoices_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceMember", b =>
                {
                    b.HasOne("WattEngine.Valve.Workspace.WtWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceRolePermission", b =>
                {
                    b.HasOne("WattEngine.Valve.Workspace.WtWorkspace", "Workspace")
                        .WithMany("RolePermissions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_role_permissions_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspaceUserPermission", b =>
                {
                    b.HasOne("WattEngine.Valve.Workspace.WtWorkspace", "Workspace")
                        .WithMany("UserPermissions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_user_permissions_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WattEngine.Valve.Workspace.WtWorkspace", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("Invoices");

                    b.Navigation("Members");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
